APP_NAME = 'ScrapyAdmin'
APP_DEBUG = True
WEB_SERVICE_PORT = 8090


PROJECT_DB_HOST = 'localhost'
PROJECT_DB_NAME = 'scrapy'
PROJECT_DB_USER = 'root'
PROJECT_DB_PASS = ''
PROJECT_DB_CHARSET = 'utf8'
PROJECT_DB_UNICODE = True


SPIDER_TYPE_START_PAGE   = 'START_PAGE'
SPIDER_TYPE_LIST_PAGE    = 'LIST_PAGE'
SPIDER_TYPE_CONTENT_PAGE = 'CONTENT_PAGE'
SPIDER_TYPE_EXTRA_PAGE = 'EXTRA_PAGE'